service: receipt-app-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_KEY: ${env:SUPABASE_SERVICE_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    SUPABASE_JWT_SECRET: ${env:SUPABASE_JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource: "arn:aws:s3:::ved-receipt-images-app/*"
  httpApi:
    cors: true

functions:
  api:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /{proxy+}
          method: any
      # Add specific routes for clarity and better configuration
      - httpApi:
          path: /receipts
          method: GET
      - httpApi:
          path: /upload
          method: POST 

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: ./.env
    include:
      - SUPABASE_URL
      - SUPABASE_SERVICE_KEY
      - S3_BUCKET_NAME
      - SUPABASE_JWT_SECRET
  serverless-offline:
    httpPort: 3001
  # Configure CORS for HTTP API properly
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - '*'  # Allow all origins as a fallback
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - Access-Control-Allow-Headers
        - Access-Control-Allow-Origin
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false  # Set to false for simplicity when using '*' in allowedOrigins
      maxAge: 86400  # 24 hours in seconds