service: receipt-app-backend

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_KEY: ${env:SUPABASE_SERVICE_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    SUPABASE_JWT_SECRET: ${env:SUPABASE_JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource: "arn:aws:s3:::ved-receipt-images-app/*"

functions:
  api:
    handler: handler.endpoint
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true  # Simplified CORS

custom:
  serverless-offline:
    httpPort: 3001